import random

TITLE_POOL = [
    "Senior Vice President of Bad Ideas",
    "Associate Producer of Unnecessary Confidence",
    "Chairperson of the Vibes Committee",
    "Director of Button Pressing",
    "Deputy Minister of Shenanigans",
    "Continuity Error Supervisor",
    "Chief Snack Auditor",
    "Intern, Department of Dubious Decisions",
    "Executive Producer of the B Plot",
    "Keeper of the Emergency Confetti",
    "Vice President of Saying Wait, What?",
    "Technical Director of Mild Panic",
    "The Person Who Said What We Were All Thinking",
    "Assistant Coordinator of Suspicious Buttons",
    "Broadcast Fellow in Questionable Timing",
    "Director of Accidental Science",
    "Field Marshal of Desk Clutter",
    "Chief Executive of Looking Busy",
    "Producer of Almost Useful Warnings",
    "Assistant to the Assistant to the Plan",
    "Director of Dramatic Cable Management",
    "Lead Consultant for Unclear Objectives",
    "Senior Analyst of Things That Went Clunk",
    "Supervisor of Off-Camera Snacks",
    "Junior Wrangler of The Third Monitor",
    "Commissioner of Beeping Equipment",
    "Associate Dean of Weird Lighting",
    "Director of Plausible Deniability",
    "Executive Chair of The Loud Noise Committee",
    "Assistant Editor of Forgotten Context",
    "Coordinator of Highly Specific Panic",
    "Head of Recreational Overthinking",
    "Vice President of Premature Applause",
    "Chief Tape Label Strategist",
    "Senior Fellow in Button Anxiety",
    "Director of Emergency Jazz Hands",
    "Lead Designer of Unnecessary Labels",
    "Assistant Producer of The Side Quest",
    "Chair of The Probably Fine Task Force",
    "Chief Inspector of Wobbly Tripods",
    "Director of Ambient Nonsense",
    "Executive Producer of The Weird Part",
    "Deputy Chief of Keeping It Rolling",
    "Lead Advisor for Maybe Try It Again",
    "Principal Investigator of Suspicious Smoke",
    "Department Head of Dramatic Pauses",
    "Night Manager of The Idea Drawer",
    "Director of Last-Minute Excellence",
    "Certified Operator of The Big Red Button",
    "Associate Wrangler of Loose Cables",
    "Senior Producer of Improvised Authority",
    "Official Noticer of Background Details",
    "Chief Procurement Officer of Tiny Props",
    "Director of Unexpected Competence",
    "Minister Without Portfolio, With Clipboard",
    "Assistant Archivist of Bad Decisions",
    "Deputy Director of Table Read Energy",
    "Lead Technician of The Humming Sound",
    "Chairperson of Questionable Props",
    "Executive Analyst of That One Noise",
    "Production Fellow in Chaotic Courtesy",
    "Key Grip of Emotional Resilience",
    "Director of Budget Thunder",
    "Senior Consultant for Very Normal Behavior",
    "Associate Producer of Suspenseful Silence",
    "Head of The Button Preservation Society",
    "Official Keeper of The Spare HDMI",
    "Vice Chancellor of Dramatic Reactions",
    "Lead Engineer of Carefully Managed Mayhem",
    "Senior Coordinator of The Cold Open",
    "Director of Broadcast Shenanigans",
    "Executive Wrangler of Wandering Topics",
    "Assistant Director of Unhelpful Confidence",
    "Chief Quality Officer of Half Plans",
    "Commissioner of The After-Hours Bit",
    "Principal Supervisor of Mystery Cables",
    "Junior Deputy of Saying Enhance",
    "Lead Strategist of Last Second Fixes",
    "Director of Reverse Countdown Energy",
    "Senior Fellow of The Mislabelled Switch",
    "Chief Archivist of The Weird Tape",
    "Official Sponsor of Loud Shirts",
    "Production Manager of The Bizarrely Specific",
    "Assistant Curator of Suspicious Props",
    "Director of Friendly Chaos",
    "Executive Producer of The Callback",
    "Key Strategist of Pretending This Was Planned",
    "Senior Operator of The Wrong Knob",
    "Associate Director of Candlelit Troubleshooting",
    "Chief Counsel for The Bit",
    "Vice President of Nodding Like We Understand",
    "Lead Diplomat to The Audio Board",
    "Assistant Producer of Background Lore",
    "Director of Maximum Side-Eye",
    "Official Witness to The Clicking Sound",
    # Night Attack & Great Night specific inside jokes
    "Chief Inspector of Chatrealm",
    "Associate Producer of The Pre-Show",
    "Director of Jury Nullification",
    "Senior Analyst of The Diamond Club",
    "Keeper of The D-Club Secret Handshake",
    "Executive Wrangler of The Green Room",
    "Head of The NSFW Committee",
    "Director of the Tumbleweed Emoji",
    "Chief Strategist of The Bit",
    "Producer of Magic Tricks Gone Right",
    "Deputy Minister of Fire Breathing",
    "Intern, Department of Spiky Hair",
    # Scam School specific inside jokes
    "Chief Mixologist of The Scam School Bar",
    "Director of Free Drinks",
    "Senior Fellow of Bar Bets",
    "Associate Producer of Matches and Coins",
    "Head of The Napkin Folding Department",
    "Executive Producer of The Missing Card",
    "Chief Auditor of Sleight of Hand",
    "Supervisor of Questionable Puzzles",
    "Lead Consultant on Winning Free Beer"
]

def get_random_title(used_titles=None):
    if used_titles is None:
        used_titles = set()
    available = [t for t in TITLE_POOL if t not in used_titles]
    if not available:
        # If all titles are used, just pull from the full pool
        available = TITLE_POOL
    return random.choice(available)
